// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ZEQUANR/zhulong/ent/students"
	"github.com/ZEQUANR/zhulong/ent/user"
)

// Students is the model entity for the Students schema.
type Students struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Avatar holds the value of the "avatar" field.
	Avatar string `json:"avatar,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// College holds the value of the "college" field.
	College string `json:"college,omitempty"`
	// Phone holds the value of the "phone" field.
	Phone string `json:"phone,omitempty"`
	// Major holds the value of the "major" field.
	Major string `json:"major,omitempty"`
	// Class holds the value of the "class" field.
	Class string `json:"class,omitempty"`
	// Number holds the value of the "number" field.
	Number string `json:"number,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StudentsQuery when eager-loading is set.
	Edges         StudentsEdges `json:"edges"`
	user_students *int
	selectValues  sql.SelectValues
}

// StudentsEdges holds the relations/edges for other nodes in the graph.
type StudentsEdges struct {
	// Users holds the value of the users edge.
	Users *User `json:"users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StudentsEdges) UsersOrErr() (*User, error) {
	if e.Users != nil {
		return e.Users, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Students) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case students.FieldID:
			values[i] = new(sql.NullInt64)
		case students.FieldAvatar, students.FieldName, students.FieldCollege, students.FieldPhone, students.FieldMajor, students.FieldClass, students.FieldNumber:
			values[i] = new(sql.NullString)
		case students.ForeignKeys[0]: // user_students
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Students fields.
func (s *Students) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case students.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case students.FieldAvatar:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar", values[i])
			} else if value.Valid {
				s.Avatar = value.String
			}
		case students.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				s.Name = value.String
			}
		case students.FieldCollege:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field college", values[i])
			} else if value.Valid {
				s.College = value.String
			}
		case students.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				s.Phone = value.String
			}
		case students.FieldMajor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field major", values[i])
			} else if value.Valid {
				s.Major = value.String
			}
		case students.FieldClass:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field class", values[i])
			} else if value.Valid {
				s.Class = value.String
			}
		case students.FieldNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field number", values[i])
			} else if value.Valid {
				s.Number = value.String
			}
		case students.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_students", value)
			} else if value.Valid {
				s.user_students = new(int)
				*s.user_students = int(value.Int64)
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Students.
// This includes values selected through modifiers, order, etc.
func (s *Students) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// QueryUsers queries the "users" edge of the Students entity.
func (s *Students) QueryUsers() *UserQuery {
	return NewStudentsClient(s.config).QueryUsers(s)
}

// Update returns a builder for updating this Students.
// Note that you need to call Students.Unwrap() before calling this method if this Students
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Students) Update() *StudentsUpdateOne {
	return NewStudentsClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Students entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Students) Unwrap() *Students {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Students is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Students) String() string {
	var builder strings.Builder
	builder.WriteString("Students(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("avatar=")
	builder.WriteString(s.Avatar)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(s.Name)
	builder.WriteString(", ")
	builder.WriteString("college=")
	builder.WriteString(s.College)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(s.Phone)
	builder.WriteString(", ")
	builder.WriteString("major=")
	builder.WriteString(s.Major)
	builder.WriteString(", ")
	builder.WriteString("class=")
	builder.WriteString(s.Class)
	builder.WriteString(", ")
	builder.WriteString("number=")
	builder.WriteString(s.Number)
	builder.WriteByte(')')
	return builder.String()
}

// StudentsSlice is a parsable slice of Students.
type StudentsSlice []*Students
