// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shplume/zhulong/ent/predicate"
	"github.com/shplume/zhulong/ent/student"
	"github.com/shplume/zhulong/ent/user"
)

// StudentUpdate is the builder for updating Student entities.
type StudentUpdate struct {
	config
	hooks    []Hook
	mutation *StudentMutation
}

// Where appends a list predicates to the StudentUpdate builder.
func (su *StudentUpdate) Where(ps ...predicate.Student) *StudentUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetName sets the "name" field.
func (su *StudentUpdate) SetName(s string) *StudentUpdate {
	su.mutation.SetName(s)
	return su
}

// SetNillableName sets the "name" field if the given value is not nil.
func (su *StudentUpdate) SetNillableName(s *string) *StudentUpdate {
	if s != nil {
		su.SetName(*s)
	}
	return su
}

// SetCollege sets the "college" field.
func (su *StudentUpdate) SetCollege(s string) *StudentUpdate {
	su.mutation.SetCollege(s)
	return su
}

// SetNillableCollege sets the "college" field if the given value is not nil.
func (su *StudentUpdate) SetNillableCollege(s *string) *StudentUpdate {
	if s != nil {
		su.SetCollege(*s)
	}
	return su
}

// SetSubject sets the "subject" field.
func (su *StudentUpdate) SetSubject(s string) *StudentUpdate {
	su.mutation.SetSubject(s)
	return su
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (su *StudentUpdate) SetNillableSubject(s *string) *StudentUpdate {
	if s != nil {
		su.SetSubject(*s)
	}
	return su
}

// SetClass sets the "class" field.
func (su *StudentUpdate) SetClass(s string) *StudentUpdate {
	su.mutation.SetClass(s)
	return su
}

// SetNillableClass sets the "class" field if the given value is not nil.
func (su *StudentUpdate) SetNillableClass(s *string) *StudentUpdate {
	if s != nil {
		su.SetClass(*s)
	}
	return su
}

// SetIdentity sets the "identity" field.
func (su *StudentUpdate) SetIdentity(s string) *StudentUpdate {
	su.mutation.SetIdentity(s)
	return su
}

// SetNillableIdentity sets the "identity" field if the given value is not nil.
func (su *StudentUpdate) SetNillableIdentity(s *string) *StudentUpdate {
	if s != nil {
		su.SetIdentity(*s)
	}
	return su
}

// SetUserIDID sets the "user_id" edge to the User entity by ID.
func (su *StudentUpdate) SetUserIDID(id int) *StudentUpdate {
	su.mutation.SetUserIDID(id)
	return su
}

// SetUserID sets the "user_id" edge to the User entity.
func (su *StudentUpdate) SetUserID(u *User) *StudentUpdate {
	return su.SetUserIDID(u.ID)
}

// Mutation returns the StudentMutation object of the builder.
func (su *StudentUpdate) Mutation() *StudentMutation {
	return su.mutation
}

// ClearUserID clears the "user_id" edge to the User entity.
func (su *StudentUpdate) ClearUserID() *StudentUpdate {
	su.mutation.ClearUserID()
	return su
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *StudentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *StudentUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *StudentUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *StudentUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *StudentUpdate) check() error {
	if _, ok := su.mutation.UserIDID(); su.mutation.UserIDCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Student.user_id"`)
	}
	return nil
}

func (su *StudentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(student.Table, student.Columns, sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(student.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.College(); ok {
		_spec.SetField(student.FieldCollege, field.TypeString, value)
	}
	if value, ok := su.mutation.Subject(); ok {
		_spec.SetField(student.FieldSubject, field.TypeString, value)
	}
	if value, ok := su.mutation.Class(); ok {
		_spec.SetField(student.FieldClass, field.TypeString, value)
	}
	if value, ok := su.mutation.Identity(); ok {
		_spec.SetField(student.FieldIdentity, field.TypeString, value)
	}
	if su.mutation.UserIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.UserIDTable,
			Columns: []string{student.UserIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.UserIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.UserIDTable,
			Columns: []string{student.UserIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{student.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// StudentUpdateOne is the builder for updating a single Student entity.
type StudentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StudentMutation
}

// SetName sets the "name" field.
func (suo *StudentUpdateOne) SetName(s string) *StudentUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (suo *StudentUpdateOne) SetNillableName(s *string) *StudentUpdateOne {
	if s != nil {
		suo.SetName(*s)
	}
	return suo
}

// SetCollege sets the "college" field.
func (suo *StudentUpdateOne) SetCollege(s string) *StudentUpdateOne {
	suo.mutation.SetCollege(s)
	return suo
}

// SetNillableCollege sets the "college" field if the given value is not nil.
func (suo *StudentUpdateOne) SetNillableCollege(s *string) *StudentUpdateOne {
	if s != nil {
		suo.SetCollege(*s)
	}
	return suo
}

// SetSubject sets the "subject" field.
func (suo *StudentUpdateOne) SetSubject(s string) *StudentUpdateOne {
	suo.mutation.SetSubject(s)
	return suo
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (suo *StudentUpdateOne) SetNillableSubject(s *string) *StudentUpdateOne {
	if s != nil {
		suo.SetSubject(*s)
	}
	return suo
}

// SetClass sets the "class" field.
func (suo *StudentUpdateOne) SetClass(s string) *StudentUpdateOne {
	suo.mutation.SetClass(s)
	return suo
}

// SetNillableClass sets the "class" field if the given value is not nil.
func (suo *StudentUpdateOne) SetNillableClass(s *string) *StudentUpdateOne {
	if s != nil {
		suo.SetClass(*s)
	}
	return suo
}

// SetIdentity sets the "identity" field.
func (suo *StudentUpdateOne) SetIdentity(s string) *StudentUpdateOne {
	suo.mutation.SetIdentity(s)
	return suo
}

// SetNillableIdentity sets the "identity" field if the given value is not nil.
func (suo *StudentUpdateOne) SetNillableIdentity(s *string) *StudentUpdateOne {
	if s != nil {
		suo.SetIdentity(*s)
	}
	return suo
}

// SetUserIDID sets the "user_id" edge to the User entity by ID.
func (suo *StudentUpdateOne) SetUserIDID(id int) *StudentUpdateOne {
	suo.mutation.SetUserIDID(id)
	return suo
}

// SetUserID sets the "user_id" edge to the User entity.
func (suo *StudentUpdateOne) SetUserID(u *User) *StudentUpdateOne {
	return suo.SetUserIDID(u.ID)
}

// Mutation returns the StudentMutation object of the builder.
func (suo *StudentUpdateOne) Mutation() *StudentMutation {
	return suo.mutation
}

// ClearUserID clears the "user_id" edge to the User entity.
func (suo *StudentUpdateOne) ClearUserID() *StudentUpdateOne {
	suo.mutation.ClearUserID()
	return suo
}

// Where appends a list predicates to the StudentUpdate builder.
func (suo *StudentUpdateOne) Where(ps ...predicate.Student) *StudentUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *StudentUpdateOne) Select(field string, fields ...string) *StudentUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Student entity.
func (suo *StudentUpdateOne) Save(ctx context.Context) (*Student, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *StudentUpdateOne) SaveX(ctx context.Context) *Student {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *StudentUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *StudentUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *StudentUpdateOne) check() error {
	if _, ok := suo.mutation.UserIDID(); suo.mutation.UserIDCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Student.user_id"`)
	}
	return nil
}

func (suo *StudentUpdateOne) sqlSave(ctx context.Context) (_node *Student, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(student.Table, student.Columns, sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Student.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, student.FieldID)
		for _, f := range fields {
			if !student.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != student.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(student.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.College(); ok {
		_spec.SetField(student.FieldCollege, field.TypeString, value)
	}
	if value, ok := suo.mutation.Subject(); ok {
		_spec.SetField(student.FieldSubject, field.TypeString, value)
	}
	if value, ok := suo.mutation.Class(); ok {
		_spec.SetField(student.FieldClass, field.TypeString, value)
	}
	if value, ok := suo.mutation.Identity(); ok {
		_spec.SetField(student.FieldIdentity, field.TypeString, value)
	}
	if suo.mutation.UserIDCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.UserIDTable,
			Columns: []string{student.UserIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.UserIDIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.UserIDTable,
			Columns: []string{student.UserIDColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Student{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{student.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
